name: Foo

on: [push]

jobs:
  # This workflow contains a single job called "build"
  koko:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run command
      env: 
        sha: ${{ github.sha }}
      run: |
        echo Hello ${sha}
